theme: jekyll-theme-minimal
repository: NCMulder/NCMulder.github.io

title: Niels Mulder
description: Some place to list the things I've worked on
author: Nielsch
logo: assets/images/logo.png
google_analytics: UA-119605097-1
permalink: pretty